### PR TITLE
fix: Clean up no-results page

### LINKED ISSUE #419: Clean up no-results page

### PR DESCRIPTION
**Pull request by o-jorgensen**
This PR will add some changes to the "No results" page:

- Change variogram/object links from `<a href>` to `<Link to>` to avoid page refresh.
- Remove the `<InfoPageComponent>` wrapper to simplify styling
- Decrease Halloween factor (remove cobweb box image)

Closes #419

### CODE REVIEW

File: src/features/Results/NoResults/NoResults.tsx [hunk 1]
```diff
@@ -1,29 +1,18 @@
...
+    <Styled.NoResults>
+      <Typography variant="h2">No results found</Typography>
+      <Typography variant="body_long">
+        Please check your compute settings for
+        <Link to={'../compute/variogram'}>variogram</Link>
+        or
+        <Link to={'../compute/object'}>object</Link>
+        cases.
+      </Typography>
+    </Styled.NoResults>
```
Comment (mheggelund) [inline src/features/Results/NoResults/NoResults.tsx:16]:
```suggestion
    <Styled.NoResults>
      <Typography variant="h2">No results found</Typography>
      <Typography variant="body_long">
        Please check your compute settings for
        {location.pathname.includes('variogram') && (
          <Link to={'../compute/variogram'}>variogram</Link>
        )}
        {location.pathname.includes('object') && (
          <Link to={'../compute/object'}>object</Link>
        )}
        case.
      </Typography>
    </Styled.NoResults>
```

File: src/features/Results/NoResults/NoResults.tsx [hunk 2]
```diff
@@ -1,29 +1,18 @@
 import { Typography } from '@equinor/eds-core-react';
-import { InfoPageComponent } from '../../../components/InfoPageComponent/InfoPageComponent';
-import NoResultPicture from './NoResults.jpeg';
 import * as Styled from './NoResults.styled';
+import { Link } from 'react-router-dom';
 
 export const NoResults = () => {
   return (
```
Comment (mheggelund) [inline src/features/Results/NoResults/NoResults.tsx:6]:
```suggestion
  return (
  const location = useLocation();


```

File: src/features/Results/NoResults/NoResults.tsx [hunk 3]
```diff
@@ -1,29 +1,18 @@
 import { Typography } from '@equinor/eds-core-react';
-import { InfoPageComponent } from '../../../components/InfoPageComponent/InfoPageComponent';
-import NoResultPicture from './NoResults.jpeg';
 import * as Styled from './NoResults.styled';
+import { Link } from 'react-router-dom';
```
Comment (mheggelund) [inline src/features/Results/NoResults/NoResults.tsx:3]:
```suggestion
import { Link, useLocation } from 'react-router-dom';
```

File: src/features/Results/NoResults/NoResults.tsx (hunk 1 above)
Comment (o-jorgensen) [reply src/features/Results/NoResults/NoResults.tsx]: Nice! I think it's cleaner and easier to use like this :)

**Review by mheggelund — APPROVED** [review]
Good work!
