### PR TITLE
Fix/compute todos

### LINKED ISSUE #157: Edit/uppdate compute case in DB

### LINKED ISSUE #194: Save variogram case and store in db

### PR DESCRIPTION
**Pull request by mheggelund**
closes #194 
closes #157

### CODE REVIEW

File: src/features/Compute/CaseGroup/CaseRow/CaseRow.tsx [hunk 1]
```diff
@@ -127,63 +114,137 @@ export const CaseRow = ({
...
+        );
+        inputSettingsList = firstUpdate;
+
+        const secondUpdate = await updateList(
+          selectedVariogramModels,
+          inputSettingsList,
+          'Net-To-Gross',
+          'Variogram Family Filter',
+        );
+        inputSettingsList = secondUpdate;
```
Comment (Sinrefvol) [inline src/features/Compute/CaseGroup/CaseRow/CaseRow.tsx:216]: how does that work and what does it do?

Comment (mheggelund) [reply src/features/Compute/CaseGroup/CaseRow/CaseRow.tsx:216]: Updates input setting list with the different selected input setting for the case to be saved. The list is send at metadata to the api on POST or PUT request for a compute case.
