### PR TITLE
fix: Variogram results table size

### LINKED ISSUE #392: Variogram results table size
Same size on the table with and without expanded row

### PR DESCRIPTION
**Pull request by o-jorgensen**
- Set a fixed table width to avoid "jumping" and repositioning of columns
- Tweak margins and spacing for better alignment
- Add tooltip icon/information in some columns
- Add a background colour to easier separate expanded rows from main rows
- Right-align numeric values

Closes #392 

---

Example screenshot with the changes in this PR:

image

### CODE REVIEW

File: src/features/Results/CaseResult/CaseResultView/VariogramCaseResult/VariogramResultTable/TanStackTable/TanStackTable.tsx [hunk 1]
```diff
@@ -279,25 +287,34 @@ export const TanStackTable = ({
...
               checked={checkedStatus(row.original)}
-              disabled={!isOwner}
-            ></Switch>
-          )
+            />
+          ) : (
+            <Tooltip title="Only model owners can change the publish status">
+              <Switch checked={checkedStatus(row.original)} disabled />
+            </Tooltip>
+          ))
```
Comment (o-jorgensen) [inline src/features/Results/CaseResult/CaseResultView/VariogramCaseResult/VariogramResultTable/TanStackTable/TanStackTable.tsx:317]: The point here was to not only disable the switch if `isOwner` is false, but to also wrap it in a Tooltip to explain why. Perhaps there is an easier way of doing it?

Comment (mheggelund) [reply src/features/Results/CaseResult/CaseResultView/VariogramCaseResult/VariogramResultTable/TanStackTable/TanStackTable.tsx:317]: Looks goodT There are several ways to solve this, but I thisk this solution looks clean and works well :D

**Review by mheggelund — APPROVED** [review]
This looks very good! Good work!
