### PR TITLE
fix: Clean up the application header

### LINKED ISSUE #425: Remove the notification icon

### LINKED ISSUE #426: Replace dummy text with new "About" text provided by Christian and Kjetil

### LINKED ISSUE #427: Add a link to Swagger (prod) on the API page

### LINKED ISSUE #428: Remove "Log out" from the user menu
In addition, remove "Logged in" and instead add the users PEPM role below their name.

Image

### PR DESCRIPTION
**Pull request by o-jorgensen**
This PR will

- Remove the notification icon
- Replace dummy text with new "About" text provided by Christian and Kjetil
- Add a link to Swagger (prod) on the API page
- Remove "Log out" from the user menu and show role instead

Closes #425, Closes #426, Closes #427, Closes #428

### CODE REVIEW

File: src/features/AppBar/Icons/Icons.tsx [hunk 1]
```diff
@@ -23,16 +16,14 @@ export const Icons = () => {
...
-          <Menu.Item>{instance.getActiveAccount()?.name}</Menu.Item>
-          <Menu.Item as={'div'}>
-            <Button onClick={() => instance.logoutRedirect()}>Log out</Button>
-          </Menu.Item>
-        </Menu.Section>
+        <Menu.Item as={'div'} className="menu-item">
+          <ul className="user-info">
+            <li className="name">{instance.getActiveAccount()?.name}</li>
+            <li className="role">[Admin|User|Reader] role</li>
+            {/* TODO add proper role name */}
```
Comment (o-jorgensen) [inline src/features/AppBar/Icons/Icons.tsx:24]: @thomaslf97 @Sinrefvol Could one of you help me display the current user's role in this popup menu?

All we need is to replace the dummy string `[Admin|User|Reader]` with the role 🙂

File: src/pages/Api/Api.tsx [hunk 2]
```diff
@@ -5,10 +5,14 @@ import { InfoPageComponent } from '../../components/InfoPageComponent/InfoPageCo
 export const Api = () => {
   return (
     <InfoPageComponent title="Using the PEPM API">
-      <Typography variant="body_long">Api to come her soon!</Typography>
+      <Typography variant="body_long">
+        For API documentation and interactive testing, please visit our Swagger
+        UI interface.
+      </Typography>
+      {/* TODO Add a link to Swagger */}
       <Typography link href="">
```
Comment (o-jorgensen) [inline src/pages/Api/Api.tsx:13]: Do we know what the link to Swagger will be in production?

If not, we could just leave this TODO comment and fix it later.

File: src/features/AppBar/Icons/Icons.tsx (hunk 1 above)
Comment (thomaslf97) [reply src/features/AppBar/Icons/Icons.tsx]: I have added roles to this branch: fix/clean-up-application-header

Comment (o-jorgensen) [reply src/features/AppBar/Icons/Icons.tsx]: Nice! Thanks 🙂

**Review by thomaslf97 — APPROVED** [review]
